version: "3.3"

services:
  erp-purchase-service:
    build: "../purchase-service"
    restart: always
    tty: true
    depends_on:
      - erp-database-service-postgresql
    env_file:
      - '../purchase-service/.env'
    ports:
      - 0.0.0.0:7002:7002
    volumes:
      - ../purchase-service:/go/src/app

  erp-database-service-postgresql:
   image: postgres:10-alpine
   restart: always
   tty: true
   volumes:
     - ../.pgdata:/var/lib/postgresql/data
   environment:
     - POSTGRES_PASSWORD=root
     - POSTGRES_DB=postgres
   ports:
     - 0.0.0.0:5432:5432
  